#!/bin/bash
# == -> compara variáveis do tipo String
# -eq -> compara variáveis do tipo inteiro

x="manha"
y="tarde"
z="manha"

# se x é igual a y e x é diferente de z
if [ $x == $y ] && [ $x != $z ]
then
	echo "São iguais x: $x e y: $y"

# se x é igual a z e x é diferente de y
elif [ $x == $z ] && [ $x != $y ]
then
	echo "São iguais x: $x e z: $z"
	
# x é diferente de y e z
else
	echo "x é diferente de y: $y e z: $z"
fi