#!/bin/bash
# == -> compara variáveis do tipo String
# -eq -> compara variáveis do tipo inteiro

x="manha"
y="manha"
z="noite"

if [ $x == $y ] && [ $x != $z ]
then
	echo "São iguais x: $x e y: $y"
elif [ $x == $z ] && [ $x != $y ]
then
	echo "São iguais x: $x e z: $z"
else
	echo "x é diferente de y: $y e z: $z"
fi